apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: fenix-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fenix-frontend
  template:
    metadata:
      labels:
        app: fenix-frontend
    spec:
      containers:
        - name: frontend-container
          image: ghcr.io/rufeton/project-fenix-frontend:0a6817e9fba727b53e5655fde8e125e99e03f9e0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3