apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: fenix-frontend
spec:
  selector:
    app: fenix-frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort